const data = {
  direction: "rtl",
  pages: [
    { src: "./pages/الغلاف.jpg", background: "#ffffffff" },
    { src: "./pages/صفحة_001.jpg", background: "#ffffffff" },
    { src: "./pages/صفحة_002.jpg", background: "#ffffffff" },
    { src: "./pages/صفحة_003.jpg", background: "#ffffffff" },
    { src: "./pages/صفحة_004.jpg", background: "#ffffffff" },
    { src: "./pages/صفحة_005.jpg", background: "#ffffffff" },
    { src: "./pages/صفحة_006.jpg", background: "#ffffffff" },
    { src: "./pages/صفحة_007.jpg", background: "#ffffffff" },
    { src: "./pages/صفحة_008.jpg", background: "#ffffffff" },
    { src: "./pages/صفحة_009.jpg", background: "#ffffffff" },
    { src: "./pages/صفحة_010.jpg", background: "#ffffffff" },
    { src: "./pages/صفحة_011.jpg", background: "#ffffffff" },
    { src: "./pages/صفحة_012.jpg", background: "#ffffffff" },
    { src: "./pages/صفحة_013.jpg", background: "#ffffffff" },
    { src: "./pages/صفحة_014.jpg", background: "#ffffffff" },
    { src: "./pages/صفحة_015.jpg", background: "#ffffffff" },
    { src: "./pages/صفحة_016.jpg", background: "#ffffffff" },
    { src: "./pages/صفحة_017.jpg", background: "#ffffffff" },
    { src: "./pages/صفحة_018.jpg", background: "#ffffffff" },
    { src: "./pages/spreadd_020_021.png", background: "#ffffffff" },
    { src: "./pages/صفحة_021.jpg", background: "#ffffffff" },
    { src: "./pages/صفحة_022.jpg", background: "#ffffffff" },
    { src: "./pages/صفحة_023.jpg", background: "#ffffffff" },
    { src: "./pages/صفحة_024.jpg", background: "#ffffffff" },
    { src: "./pages/صفحة_025.jpg", background: "#ffffffff" },
    { src: "./pages/صفحة_026.jpg", background: "#ffffffff" },
    { src: "./pages/صفحة_027.jpg", background: "#ffffffff" },
    { src: "./pages/صفحة_028.jpg", background: "#ffffffff" },
    { src: "./pages/صفحة_029.jpg", background: "#ffffffff" },
    { src: "./pages/صفحة_030.jpg", background: "#ffffffff" },
    { src: "./pages/صفحة_031.jpg", background: "#ffffffff" },
    { src: "./pages/صفحة_032.jpg", background: "#ffffffff" },
    { src: "./pages/صفحة_033.jpg", background: "#ffffffff" },
    { src: "./pages/صفحة_034.jpg", background: "#ffffffff" },
    { src: "./pages/صفحة_035.jpg", background: "#ffffffff" },
    { src: "./pages/صفحة_036.jpg", background: "#ffffffff" },
    { src: "./pages/صفحة_037.jpg", background: "#ffffffff" },
    { src: "./pages/صفحة_038.jpg", background: "#ffffffff" },
  ],
};
